name: Devoria
version: '${project.version}'
api-version: 1.19
main: me.devoria.Devoria
authors: [ ptobey, SleepingRaven ]

commands:
  item:
    description: Get a custom item
    usage: Put an item name
  reveal:
    descreption: Changes item atty
    usage: Reveal item
  register:
    description: register player in database
  getinfo:
    description: Gets an item's meta data
  loot:
    description: Get random loot
  identify:
    description: Identifies an item
  summonmob:
    description: Summons a mob
