name: Devoria
version: '${project.version}'
main: me.devoria.core.Core
authors: [ ptobey | Lucas souza ]

commands:
  class:
    description: Select a class
    usage: huntsman/sorcerer/bard/knight
  item:
    description: Get a custom item
    usage: Put an item name
  reveal:
    descreption: Changes item atty
    usage: Reveal item
  register:
    description: register player in database



